// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PINSignature.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This generated code file was modified to compatiable with @inlinable decl.

//
//  PINSignature.proto
//  personal-identification
//
//  Created by Arkivili Collindort on 27/12/2025

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

@usableFromInline
struct PINSignature: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.
    
    @usableFromInline
    var familyName: String = String()
    
    @usableFromInline
    var givenName: String = String()
    
    @usableFromInline
    var department: String = String()
    
    @usableFromInline
    var mrz: String = String()
    
    @usableFromInline
    var unknownFields = SwiftProtobuf.UnknownStorage()
    
    @usableFromInline
    init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PINSignature: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    @usableFromInline
    static let protoMessageName: String = "PINSignature"
    
    @usableFromInline
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}family_name\0\u{3}given_name\0\u{1}department\0\u{2}\u{6}mrz\0")
    
    @usableFromInline
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularStringField(value: &self.familyName) }()
            case 2: try { try decoder.decodeSingularStringField(value: &self.givenName) }()
            case 3: try { try decoder.decodeSingularStringField(value: &self.department) }()
            case 9: try { try decoder.decodeSingularStringField(value: &self.mrz) }()
            default: break
            }
        }
    }
    
    @usableFromInline
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.familyName.isEmpty {
            try visitor.visitSingularStringField(value: self.familyName, fieldNumber: 1)
        }
        if !self.givenName.isEmpty {
            try visitor.visitSingularStringField(value: self.givenName, fieldNumber: 2)
        }
        if !self.department.isEmpty {
            try visitor.visitSingularStringField(value: self.department, fieldNumber: 3)
        }
        if !self.mrz.isEmpty {
            try visitor.visitSingularStringField(value: self.mrz, fieldNumber: 9)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    @usableFromInline
    static func ==(lhs: PINSignature, rhs: PINSignature) -> Bool {
        if lhs.familyName != rhs.familyName {return false}
        if lhs.givenName != rhs.givenName {return false}
        if lhs.department != rhs.department {return false}
        if lhs.mrz != rhs.mrz {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}

